apiVersion: v1
kind: Service
metadata:
  name: devops-q2
  labels:
    app: devops-q2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
    protocol: TCP
  selector:
    app: devops-q2
